// Generated semantic actions header for json
#pragma once

typedef enum {
    JSON_ACTION_CREATE_BOOLEAN,
    JSON_ACTION_CREATE_NUMBER,
    JSON_ACTION_CREATE_NULL,
    JSON_ACTION_CREATE_STRING,
    JSON_ACTION_CREATE_ARRAY_ELEMENTS,
    JSON_ACTION_CREATE_OPTIONAL_ARRAY_ELEMENTS,
    JSON_ACTION_CREATE_ARRAY,
    JSON_ACTION_CREATE_MEMBER,
    JSON_ACTION_CREATE_OBJECT_ELEMENTS,
    JSON_ACTION_CREATE_OPTIONAL_OBJECT_ELEMENTS,
    JSON_ACTION_CREATE_OBJECT,
    JSON_AST_ACTION_COUNT__,
} json_semantic_action_t;
