name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive' # Required for FetchContent to work

    - name: Install Doxygen
      run: sudo apt-get update && sudo apt-get install -y doxygen

    - name: Install Graphviz
      run: sudo apt-get install -y graphviz

    - name: Install LSP dependencies
      run: |
        sudo apt-get install -y libjson-c-dev
        git clone --depth 1 https://github.com/openwrt/libubox.git
        cmake -S libubox -B libubox/build -DBUILD_LUA=OFF
        cmake --build libubox/build
        sudo cmake --install libubox/build

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DBUILD_EXAMPLES=ON -DWITH_UNIT_TESTS=ON -DBUILD_GDL_LSP=ON

    - name: Build
      run: cmake --build ${{github.workspace}}/build

    - name: Test
      run: ctest --test-dir ${{github.workspace}}/build